### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [benjamin-firth/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

`We only ever want to make one 'Initial Commit'. The other commits should describe what kind of update you made and it should begin with a capital letter and be present tense. `

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object.
`For the final two methods we would want to return a true or a false instead of a yes or a no.`
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
`These all represent actions, but the naming can be better. For example `end_ringing` is a more desirable naming choice than 'ends_ringing'. 'weekend_schedule` does not clearly represent a calculation, because it isn't a verb or action phrase. Go ahead and implement changes to your method names, and make your commit with a proper commit message.`

- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
`Once again we would want to return true or false in some of these situations, and some we would want more elaborate descriptions of the return. A better attribute that could be modified by both start and end ringing is simply a 'ringing' attribute that is true or false and that those methods alter. Go ahead and redesign this class to implement this kind of logic. And, update your method return values.`

- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
